name: mango_artifact
version: 1.0.0
description: Wrapper for Artifact API
repository: https://github.com/louisevanderlith/artifact
homepage: https://github.com/louisevanderlith/artifact
environment:
  sdk: '>=2.0.0 < 3.0.0'
dependencies:
  mango_ui: '^1.0.1'